config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'
  root 'welcome#index'
  match 'auth/:provider/callback', to: 'sessions#create',:via => [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout',:via => [:get]
  
  get 'welcome/admin' => 'welcome#admin'

  get 'submissions/new' => 'submissions#new'

  match 'like', to: 'likes#like', via: :post
  match 'unlike', to: 'likes#unlike', via: :post

  resources :products

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :users
  belongs_to :products
  validates :user_id, uniqueness: { scope: :product_id }
end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :likes, dependent: :destroy
  has_many :users, through: :likes
  validates :price, :numericality => {:greater_than_or_equal_to => 0}
  
  def self.category_types
    ['Apparel', 'Accessories', 'Tech']
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :likes, dependent: :destroy
  has_many :products, through: :likes

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider 
      user.uid      = auth.uid
      user.name     = auth.info.name

      if user.uid == ENV["admin_uid"]
        user.admin = true
      else
        user.admin = false
      end

      user.save

    end
  end
  
  def like!(product)
    self.likes.create!(product_id: product.id)
  end

  def unlike!(product)
    like = self.likes.find_by_product_id(product.id) 
    like.destroy!
  end

  def like?(product)
    self.likes.find_by_product_id(product.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #before_filter :require_user

  helper_method :get_access_token

  def get_access_token
    session[:access_token]
  end


  private

  # def require_user
  #   redirect_to root_path unless current_user
  # end
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize_admin
    redirect_to root_path, :status => 401 unless current_user.admin
  end
  
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

respond_to :js, :html

  def like
    @user = current_user
    @product = Product.find(params[:product_id])
    @user.like!(@product)
  end

  def unlike
    @user = current_user
    @like = @user.likes.find_by_product_id(params[:product_id])
    @product = Product.find(params[:product_id])
    @like.destroy!
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_filter :authorize_admin, only: [:index]
  respond_to :html, :json
  
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @product.image = params[:url]
    @product.handle = params[:handle]
  end

  def create
    @product = Product.create(product_params)
    redirect_to products_path
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update_attributes(product_params)
    respond_with @product
  end

  def show
    @product = Product.find(params[:id])
  end

  
  private

  def product_params
    params.require(:product).permit(:image, :price, :name, :handle, :description, :featured, :category)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def create
     user = User.from_omniauth(env["omniauth.auth"])
     session[:access_token] = env["omniauth.auth"].credentials.token
     if(user.uid == "1746672786")
        session[:user_id] = user.id
        redirect_to '/products'
     else 
      session[:user_id] = user.id
      redirect_to root_url
     end
  end

  def destroy
     session[:user_id] = nil
     redirect_to root_url
  end
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController

  def new
    @product = Product.new
  end

  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    #@recent = Instagram.user_recent_media("225240798", count: 20)
    if params[:category].present?
      @featured = Product.where(featured: true, category: params[:category])
    else
      @featured = Product.where(featured: true)
    end
  end

  def omniauth_failure
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BaeBox</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,user-scalable=no">
    <link href='http://fonts.googleapis.com/css?family=Lato:400,700|Satisfy|Montserrat' rel='stylesheet' type='text/css'>
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/favicon.ico" type="image/x-icon">
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="visible-xs navbar-brand navbar-brand-xs" href="/">BaeBox</a>
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    
    <div id="navbar" class="navbar-collapse collapse">
        <div class="navbar-brand centered-brand hidden-xs">
          <div class ="brand"><%= link_to "BaeBox", root_path %></div> 
        </div>

        <ul class="nav navbar-nav">
          <li><%= link_to "Submit", {controller: "submissions", action: "new"} %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% Product.category_types.each do |cat| %>
                <li>
                  <%= link_to cat, root_path(category: cat) %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>
          
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>
            <li><a>Hello <%= current_user.name %></a></li>
            <li><%= link_to "Sign out", signout_path %></li>
          <% else %>
            <li><%= link_to "Log in with Instagram", "/auth/instagram" %></li>
          <% end %>
        </ul>

      </div>
    </div>
  </nav>

<%= yield %>

</body>
</html>

app/views/likes/_likebutton.html.erb
<% if current_user %>
  <% if current_user.like?(product) %>
    <%= link_to unlike_path(product_id: product.id), remote: true, class: "liked", "data-product-id": product.id, :method => :post do %><i class="fa fa-heart fa-1"></i><%end%>
  <% else %>
    <%= link_to like_path(product_id: product.id), remote: true, class: "unliked", "data-product-id": product.id,  :method => :post do %><i class="fa fa-heart fa-1"></i><% end %>
  <% end %>

<% else %>
  
<% end %>

app/views/likes/like.js.erb
// var btn = $("input.like-action[data-product-id='" + <%= @product.id %> + "']");

// btn.val('Unlike');
// btn.removeClass('like-action');
// btn.addClass('unlike-action');
// var parent = btn.parent('form');
// parent.attr('action', '/unlike?product_id=' + <%= @product.id %>);

var btn = $(".unliked[data-product-id='" + <%= @product.id %> + "']");
btn.attr('href', '/unlike?product_id=' + <%= @product.id %>);
btn.removeClass('unliked');
btn.addClass('liked');

// Now update like-count
var likeCount = $(".like-quantity[data-product-id='" + <%= @product.id %> + "']");
likeCount.html("+" + '<%= @product.likes.count %>');

app/views/likes/unlike.js.erb
// var btn = $("input.unlike-action[data-product-id='" + <%= @product.id %> + "']");

// btn.val('Like');
// btn.removeClass('unlike-action');
// btn.addClass('like-action');
// var parent = btn.parent('form');
// parent.attr('action', '/like?product_id=' + <%= @product.id %>);

var btn = $(".liked[data-product-id='" + <%= @product.id %> + "']");
btn.attr('href', '/like?product_id=' + <%= @product.id %>);
btn.removeClass('liked');
btn.addClass('unliked');

var likeCount = $(".like-quantity[data-product-id='" + <%= @product.id %> + "']");
likeCount.html("+" + '<%= @product.likes.count %>');

app/views/products/index.html.erb
<!DOCTYPE html>
<html>
<head>

</head>
<body>

    <section class="instagram-wrap">
      <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="instagram-content">
                    <h3>Available Products</h3>
                <div class="row">
                  <% @products.each do |product| %>
                    <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                        <div class = "photo-box">
                          <div class = "image-wrap">
                            <%= image_tag(product.image) %>
                          </div>
                          <div class="admin description">Handle: @<%= best_in_place product, :handle %>
                          <div class = "price">Description: <%= best_in_place product, :description %>

                          <div class = "price">Category: <%= best_in_place product, :category, type: :select, :collection => {Apparel: "Apparel", Tech: "Tech", Accessories: "Accessories"} %></div>
                        

                          <div class= "price"> Image Link: <%=  best_in_place product, :image, :display_with => :truncate, :helper_options => { :length => 20 } %>
                          <div class="price">Price: <%= best_in_place product, :price %></div>
                          <div>Feature?: <%= best_in_place product, :featured, as: :checkbox, collection: {false: "No", true: "Yes"} %> </div>
                            </div>
                        </div>
                        </div>
                        </div>
                    </div>
                    <%end %>
                </div>
              </div>
          </div>
        </div>
    </div>
    </section>

    <footer>
    </footer>
    <section class="footer-bottom">
   
    </section>
 
</body>
</html>

app/views/products/new.html.erb
<div class = "container">
  <div class = "product-container">
  <%= simple_form_for @product do |f| %>
    <%= f.input :handle %>
    <%= f.input :name %>
    <%= f.input :description %>
    
    <% if @product.image.blank? %>
      <%= f.input :image %>
    <% else %>
      <%= image_tag(@product.image) %>
      <%= f.input :image, :as => "hidden" %>
    <% end %>

    <%= f.input :price %>
    
    <%= f.check_box :featured %> Featured
    <div><%= f.button :submit %></div>
  <% end %>
</div>
</div>

app/views/products/show.html.erb
<!DOCTYPE html>
<html>
<head>

</head>
<body>

<section>

  <div class="container-fluid border">
    <div class = "row product-container border">
      <div class = "col-md-4 col-md-offset-2">
          <%= image_tag @product.image, class: "img-responsive product-image center-block" %>
      </div>
      <div class = "col-md-4">
          <div class = "product-description-text"><%= @product.description %></div>
          <div class = "by-text">By @<%= link_to @product.handle, "http://instagram.com/#{@product.handle}/", :target => '_blank'%></div>
          <div class = "price-text">Buy it for <%= number_to_currency(@product.price, :precision =>0) %></div>

          <div class = "like-list">
          Liked by:
            <div class = "names">
              <% @product.likes.each do |liker| %>
                <div class = "names"><%= User.find(liker.user_id).name %>
                </div>
              <% end %>
            </div>
          </div>

      </div>
    </div>
  </div>

</section>
 
</body>
</html>

app/views/submissions/new.html.erb
<div class = "container">
  <form class = "submit-form-container" id="submit-form">
    <div class = "box">
      <div class="input-group input-group-lg">
        
        <span class="input-group-addon" id="basic-addon1">@</span>
        <input type="text" class="form-control" id="handle-search-text" placeholder="Enter handle" aria-describedby="basic-addon1">
        <input type="hidden" id="hidden-access" value="<%= get_access_token %>"/>
        <span class="input-group-btn">
          <input type="submit" class="btn btn-default" data-something="some value" id="find-images-button" value="Find Images"/>
        </span>
      
      </div>
    </div>
    <div class = "container">
      <div class = "image-select-option-container" id="search-images-section">
        <% (0..5).each do |i| %>
          <%= link_to new_product_path() do %>
            <img src='' id=<%="product-image-#{i}" %> />
          <% end %>
        <% end %>

      </div>
    </div>
  </form>
</div>

app/views/welcome/admin.html.erb
<!DOCTYPE html>
<html>
<head>

</head>
<body>

<section>
 <div class = "admin-title"> BaeBox Admin Panel </div>
 
</section>
 
</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>

</head>
<body>

  <section class ="welcome-text">
    <div class = "container">
      <div class = "row hidden-xs">
        Curated shoppable products on Instagram.
      </div>
      <div class = "row mobile-welcome-text visible-xs">
        Curated shoppable products on Instagram.
      </div>
    </div>
  </section>

    <section class="instagram-wrap">
      <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <div class="instagram-content">
                    <h3>Featured Items</h3>
                    <div class="row">
                    <% @featured.each do |feature| %>
                      <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
                          <div class = "photo-box">
                            <div class = "fade-wrap">
                              <div class = "image-wrap">
                                <%= link_to image_tag(feature.image), {controller: "products", action: "show", id: feature.id} %>
                              </div>  
                              
                              <div class = "likebutton likebutton-fade">
                              <%= render partial: "likes/likebutton", locals: { product: feature } %>
                              </div>
                              
                              <div class = "like-quantity" data-product-id = "<%= feature.id %>">
                               +<%= feature.likes.count %>
                              </div>

                            </div>

                                <div class="description"><%= feature.description %>
                                  <div class="price"><%= number_to_currency(feature.price, :precision => 0)%></div>
                                  <div class="price">By @<%= link_to feature.handle, "http://instagram.com/#{feature.handle}/", :target => '_blank'%> </div>

                                </div>
                          </div>
                      </div>
                      <%end %>
                  </div>
                </div>
            </div>
        </div>
    </div>
    </section>

    <footer>
    </footer>
    <section class="footer-bottom">
   
    </section>
 
</body>
</html>